config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  root to: "spooners#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :spooners do
    resources :bookings, only: %i[new create]
    resources :reviews, only: %i[create]
  end
  resources :bookings, only: [:destroy]
  get "/bookings/my_bookings", to: "bookings#my_bookings"
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :spooner
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :spooner
  belongs_to :user
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/spooner.rb
class Spooner < ApplicationRecord
  has_many_attached :img
  SPOON_TYPE = ["big spoon", "little spoon", "any spoon"]
  GENDER = ["male", "female", "other"]
  validates :name, :spoon_type, :price, :gender, :age, presence: true
  validates :spoon_type, inclusion: { in: SPOON_TYPE }
  validates :gender, inclusion: { in: GENDER }
  validates :price, :age, numericality: { only_integer: true }
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def average_rating
    sum_ratings = reviews.reduce(0) { |sum, review| sum + review.rating }
    average = sum_ratings.fdiv(reviews.size)
    # round to nearest 0.5
    (average * 2.0).round / 2.0
  end

  def solid_stars
    average_rating.to_i
  end

  def half_stars
    remainder = average_rating % 1
    if remainder.zero?
      return 0
    else
      return 1
    end
  end

  def empty_stars
    5 - solid_stars - half_stars
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  SPOON_TYPE = ["big spoon", "little spoon", "any spoon"]
  GENDER = ["male", "female", "other"]
  validates :first_name, :spoon_type, :gender, :age, presence: true
  validates :spoon_type, inclusion: { in: SPOON_TYPE }
  validates :gender, inclusion: { in: GENDER }
  validates_numericality_of :age, only_integer: true
  has_many :bookings, dependent: :destroy
  has_many :spooners, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :authenticate_user!, only: :home
  include Pundit::Authorization
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :gender, :spoon_type, :age])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :gender, :spoon_type, :age])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_spooner, :set_user, only:[:new, :create]

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.spooner = @spooner
    @booking.user = @user # @review.user = current_user
    authorize @booking
    if @booking.save
      redirect_to spooner_path(@spooner)
    else
      render "spooners/new"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    authorize @booking
    redirect_to "/bookings/my_bookings"
  end

  def my_bookings
    @bookings = current_user.bookings.order(date: :desc)
    @pending_bookings = @bookings.where(pending: true)
    @active_bookings = @bookings.where(pending: false)
    authorize @bookings

    # bookings.date = @bookings do
    # @past_bookings =
    # @past_bookings = past_bookings(@bookings)
  end

  # def past_bookings(bookings)
  #   past = []
  #   bookings.each do |booking|
  #     new_date = booking.date.split("T").join(" ")
  #     puts new_date
  #     DateTime.strptime(new_date)
  #     if booking.date.past?
  #       past << booking
  #     end
  #   end
  #   return past
  # end

  private

  def booking_params
    params.require(:booking).permit(:date, :details)
  end

  def set_spooner
    @spooner = Spooner.find(params[:spooner_id])
  end

  def set_user
    @user = User.find(current_user.id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_spooner, only: %i[create]

  # def new
  #   @review = Review.new
  # end

  def create
    @review = Review.new(review_params)
    @review.spooner = @spooner
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to spooner_path(@spooner)
    else
      render "spooners/show", status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    authorize @review
    redirect_to spooner_path(@review.spooner), status: :see_other
  end

  private

  def set_spooner
    @spooner = Spooner.find(params[:spooner_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/spooners_controller.rb
class SpoonersController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home, :index, :show, :new, :create, :edit, :update, :destroy]
  before_action :set_spooner, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @spooners = Spooner.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @spooners = Spooner.all
    end
    # The `geocoded` scope filters only flats with coordinates
    @markers = @spooners.geocoded.map do |spooner|
      {
        lat: spooner.latitude,
        lng: spooner.longitude,
        info_window: render_to_string(partial: "info_window", locals: {spooner: spooner }),
        image_url: helpers.asset_url("purple.png")
      }
    end
    authorize @spooners
  end

  def show
    @review = Review.new
    authorize @spooner
    authorize @review
  end

  def new
    @spooner = Spooner.new
    authorize @spooner
  end

  def create
    @spooner = Spooner.new(spooner_params)
    @spooner.user = current_user
    authorize @spooner
    if @spooner.save
      redirect_to spooner_path(@spooner)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def home
    index
  end

  def edit
    authorize @spooner
  end

  def update
    @spooner.update(spooner_params_no_img)
    if params[:spooner][:img] != [""]
      params[:spooner][:img].each do |image|
        @spooner.img.attach(image)
      end
    end
    authorize @spooner
    redirect_to spooner_path(@spooner)
  end

  def destroy
    @spooner.destroy
    authorize @spooner
    redirect_to spooners_path, status: :see_other
  end

  private

  def spooner_params
    params.require(:spooner).permit(:name, :age, :spoon_type, :gender, :price, :overview, img: [])
  end

  def spooner_params_no_img
    params.require(:spooner).permit(:name, :age, :spoon_type, :gender, :price, :overview)
  end

  def set_spooner
    @spooner = Spooner.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new-booking.html.erb
<div class="container">
  <h2><%=  "New Booking with #{@spooner.name}" %> </h2>
  <%= simple_form_for [@spooner, @booking] do |f| %>
  <%= f.datetime_field :date %>
  <%= f.input :details %>
  <%= f.submit %>
  <% end %>
</div>

app/views/bookings/my_bookings.html.erb
<div class="container mb-6">
  <h2> Your Pending Bookings</h2>
  <div class="d-flex py-4">
    <div class="row my-2 justify-content-between">
      <% @pending_bookings.each do |booking| %>
        <div class="card col-3 rounded d-flex justify-content-between m-1" style="width: 280px; padding: 0px;">
          <% if booking.spooner.img.attached? %>
            <%= cl_image_tag booking.spooner.img.first.key, height: 280, width: 279, crop: :fill, class: "w-100 border-bottom" %>
          <% else %>
            <%= image_tag "person-placeholder.jpg",  width: 279 , height: 280, crop: :fill %>
          <% end %>
          <div class="card-body" style="background-color: rgb(255,143,177,0.2); padding: 10px 15px;">
            <div class='row'>
              <p class="card-text d-flex align-items-center" style="margin-bottom: 0px; color: black; font-size: 20px;"><strong><%=link_to booking.spooner.name, spooner_path(booking.spooner), class: "text-decoration-none"%></strong></p>
              <div class="col-10">
                <p class="card-text"> <%= booking.details %></p>
                <p class ="card-text m-0"> <strong> <%= "Date: " + "#{booking.date.split('T')[0]}" %> </p> </strong>
                <p class ="card-text m-0"> <strong> <%= " Time: #{booking.date.split('T')[1]} "  %> </p> </strong>
              </div>
              <div class="col-2 d-flex align-items-end justify-content-end">
                <%= link_to booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Delete Booking?"} do %>
                <%= image_tag "xspoons-purple.png", width: "30px", alt: "Delete" %>
                <% end %>
                <%# <ul class="list-group list-group-flush"> %>
                    <%# <li class="list-group-item mb-2"> <strong> <%= "Date: #{booking.date}" </strong></li> %>
                <%# </ul> %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <h2>Your Active Bookings</h2>
  <div class="d-flex py-4">
    <div class="row my-2 justify-content-between">
      <% @active_bookings.each do |booking| %>
        <div class="card col-3 rounded d-flex justify-content-between m-1" style="width: 280px; padding: 0px;">
          <% if booking.spooner.img.attached? %>
            <%= cl_image_tag booking.spooner.img.first.key, height: 280, width: 279, crop: :fill, class: "w-100 border-bottom" %>
          <% else %>
            <%= image_tag "person-placeholder.jpg",  width: 279 , height: 280, crop: :fill %>
          <% end %>
          <div class="card-body" style="background-color: rgb(255,143,177,0.2); padding: 10px 15px;">
            <div class='row'>
              <p class="card-text d-flex align-items-center" style="margin-bottom: 0px; color: black; font-size: 20px;"><strong><%=link_to booking.spooner.name, spooner_path(booking.spooner), class: "text-decoration-none"%></strong></p>
              <div class="col-10">
                <p class="card-text"> <%= booking.details %></p>
                <p class ="card-text m-0"> <strong> <%= "Date: " + "#{booking.date.split('T')[0]}" %> </p> </strong>
                <p class ="card-text m-0"> <strong> <%= " Time: #{booking.date.split('T')[1]} "  %> </p> </strong>
              </div>
              <div class="col-2 d-flex align-items-end justify-content-end">
                <%= link_to booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Cancel Spooning Session?"} do %>
                <%= image_tag "xspoons-purple.png", width: "30px", alt: "Cancel" %>
                <% end %>
                <%# <ul class="list-group list-group-flush"> %>
                    <%# <li class="list-group-item mb-2"> <strong> <%= "Date: #{booking.date}" </strong></li> %>
                <%# </ul> %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <h2>Your past bookings</h2>

</div>

app/views/bookings/new.html.erb
<%= render "new-booking", booking: @booking %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spoonies</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400&display=swap" rel="stylesheet">
    <script src="https://code.iconify.design/iconify-icon/1.0.1/iconify-icon.min.js"></script>
    <style>
      #footer {
      position: fixed;
      bottom: 0;
      width: 100%;
      padding: 5px;
      height: 50px;
    }
  </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg" style="background-color: #432c7a;">
      <div class="container-fluid">
        <a class="navbar-brand" style="color: ##FF8FB1;" href="#" >
        <%= link_to (spooners_path) do%>
        <%= image_tag "spoonies-filled.png", width:"150"%>
        <% end %>
        </a>
        <button class="navbar-toggler" style="background-color: #FCE2DB; color: #FCE2DB;" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ms-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
            <%= link_to "My Bookings", bookings_my_bookings_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <% if current_user.spooners.empty? %>
              <%= link_to "Become a Spooner", new_spooner_path, class: "nav-link"  %>
              <% else %>
              <%= link_to "My Spooner Profile", spooner_path(current_user.spooners.first), class: "nav-link"  %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", '/users/sign_up', class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About Us</a>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= render "shared/flashes" %>
    <%= yield %>
    <%# footer %>
    <div class="spoonies-footer" id="footer" style="background-color: #432c7a;">
      <footer class="d-flex flex-wrap align-items-center justify-content-between">
        <p class="col-md-4 mb-0" style="color: #FF8FB1;"> © Spoonies 2022 </p>

        <a href="#" class="d-flex align-items-center justify-content-center">
          <%= image_tag "spoons-filled.png", width:"20", class:"d-inline-block align-middle"%>
        </a>

        <ul class="nav col-md-4 justify-content-end text-decoration-none" style="color: #FCE2DB;">
          <li class="nav-item"><p href="#" class="px-2">Help</p></li>
          <li class="nav-item"><p href="#" class="px-2">FAQs</p></li>
          <li class="nav-item"><p href="#" class="px-2">Spoon Crew</p></li>
          <li class="nav-item"><p href="#" class="px-2">Contact Us</p></li>
        </ul>
      </footer>
    </div>
  </body>
</html>

app/views/reviews/_new.html.erb
<div class="container pb-3">
<%= simple_form_for [spooner, review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-light" %>
<% end %>
</div>

app/views/shared/_flashes.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/spooners/_form.html.erb
<%= simple_form_for(spooner) do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :gender, collection: Spooner::GENDER %>
  <%= f.input :spoon_type, collection: Spooner::SPOON_TYPE %>
  <%= f.input :price %>
  <%= f.input :overview %>
  <%= f.input :img, as: :file, input_html: { multiple: true } %>
  <%= f.button :submit, "Spoon Me Up", id:"form-submit-btn" %>
<% end %>

app/views/spooners/_home.html.erb
<div class="container mb-5">
  <%= render "search", spooner: spooner %>

  <div class="d-flex py-4">
    <div class="row my-2 justify-content-between">
      <% spooners.each do |spooner| %>
        <div class="col-lg-3 mb-4" >
          <div class="card d-flex justify-content-between h-100">
            <% if spooner.img.attached? %>
              <div class="w-100" style="aspect-ratio: 1; background-image: url('<%= cl_image_path spooner.img.first.key,  width: 500 %>'); background-size: cover;"></div>
            <% else %>
              <div class="w-100" style="aspect-ratio: 1; background-image: url('<%= image_path "person-placeholder.jpg",  width: 500 %>'); background-size: cover;"></div>
            <% end %>
            <div class="card-body" style="background-color: rgb(255,143,177,0.2); padding: 10px 15px;">
              <div class="row">
                <p class="card-text d-flex align-items-center" style="margin-bottom: 0px; color: black; font-size: 20px;"><strong><%=link_to spooner.name, spooner_path(spooner), class: "text-decoration-none"%></strong></p>
                <div class="col-10">
                  <p class="card-text d-flex align-items-center" style="margin-bottom: 0px; color: black;"><iconify-icon icon="mdi:silverware-spoon"></iconify-icon><%=spooner.spoon_type.capitalize%></p>
                  <p class="card-text d-flex align-items-center" style="margin-bottom: 0px; color: black;"><iconify-icon icon="bx:male-female"></iconify-icon><%=spooner.gender.capitalize%></p>
                  <% if spooner.reviews.size > 0 %>
                  <p class="card-text d-flex align-items-center" style="margin-bottom: 0px; color: black;">
                  <% spooner.solid_stars.times do %>
                  <iconify-icon icon="material-symbols:star"></iconify-icon>
                  <% end %>
                  <% spooner.half_stars.times do %>
                  <iconify-icon icon="material-symbols:star-half"></iconify-icon>
                  <% end %>
                  <% spooner.empty_stars.times do %>
                  <iconify-icon icon="material-symbols:star-outline"></iconify-icon>
                  <% end %>
                  </p>
                  <% end %>
                </div>
                  <div class="col-2 lg-6 d-flex align-items-center justify-content-end">
                    <p class="card-text" style="margin-bottom: 0px; color: black; font-size: 36px;">$<%=spooner.price%></p>
                  </div>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>

  <div style = "margin-bottom: 100px; text-align:center; margin-bottom: 100px;">
    <div style="margin-bottom: 40px;">
    <h1>🥄 Local Spooners near you! 🥄</h1>
    </div>
    <div style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/spooners/_info_window.html.erb
  <div class="card col-3 rounded d-flex justify-content-between mb-4" style="width: 200px; padding: 0px; margin-left: -10px; margin-top: -10px;">
    <div class=thing>
    <%= link_to spooner_path(spooner), style:"z-index: 1000;" do%>
    <% if spooner.img.attached? %>
        <%= cl_image_tag spooner.img.first.key, height: 140, width: 199, crop: :fill %>
    <% else %>
      <%= image_tag "person-placeholder.jpg",  width: 199 , height: 140, crop: :fill %>
    <% end %>
    <% end %>
    <div class="card-body" style="background-color: rgb(255,143,177,0.2); padding: 10px 15px;">
      <div class="row">
        <p class="card-text d-flex align-items-center" style="margin-bottom: 0px; color: black; font-size: 20px;"><strong><%=link_to spooner.name, spooner_path(spooner), class: "text-decoration-none"%></strong></p>
        <div class="col-10">
          <p class="card-text d-flex align-items-center" style="margin-bottom: 0px; color: black;"><iconify-icon icon="mdi:silverware-spoon"></iconify-icon><%=spooner.spoon_type.capitalize%></p>
          <p class="card-text d-flex align-items-center" style="margin-bottom: 0px; color: black;"><iconify-icon icon="bx:male-female"></iconify-icon><%=spooner.gender.capitalize%></p>
          <% if spooner.reviews.size > 0 %>
          <p class="card-text d-flex align-items-center" style="margin-bottom: 0px; color: black;"><iconify-icon icon="material-symbols:star"></iconify-icon>
          <%= (spooner.reviews.reduce(0) { |sum, review| sum + review.rating }).fdiv(spooner.reviews.size) %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spooners/edit.html.erb
<div class="container mb-5">
  <h1>Update Spooner Profile</h1>
  <%= render "form", spooner: @spooner %>
</div>

app/views/spooners/home.html.erb
<%= render "home", spooners: @spooners, spooner: @spooner %>

app/views/spooners/index.html.erb
<%= render "home", spooners: @spooners, spooner: @spooner %>

app/views/spooners/show.html.erb
  <body style="background-color:#FCE2DB opacity:0.6;">
    <div class="d-flex p-2 m-8 justify-content-center">
      <h1> 🥄 <%= @spooner.name %> 🥄 </h1>
    </div>
    <div class="container">
    <div class="row">
        <div class="col-lg-6 p-4 justify-content-center">
        <% if @spooner.img.attached? %>
          <% @spooner.img.each do |photo| %>
            <div><%= cl_image_tag photo.key, height: 300, width: 500, crop: :fill, :style => "margin-bottom: 16px; border-radius: 16px" %></div>
          <% end %>
        <% else %>
        <%= image_tag "person-placeholder.jpg", width: 500 %>
      <% end %>
      </div>
      <div class="col-lg-6 p-4 m-10 justify-content-center">
        <div class="p-4" style="border-style:solid; border-radius: 16px;">
          <h4 style="color:#80489C;" class="mb-3">Age: <%= @spooner.age %> years</h4>
          <h4 style="color:#80489C;" class="mb-3">Gender: <%= @spooner.gender %></h4>
          <h4 style="color:#80489C;" class="mb-3">Prefers to be: <%= @spooner.spoon_type %></h4>
          <h4 style="color:#80489C;" class="mb-3">Price: $<%= @spooner.price %></h4>
          <h4 style="color:#80489C;" class="mb-3">Details: <%= @spooner.overview %></h4>
        </div>
        <div class="mt-5 p-2 d-flex justify-content-between align-items-center">
          <% if policy(@spooner).edit? %>
            <button class="btn btn-show"><%= link_to "Edit Spooner", edit_spooner_path(@spooner) %>
            </button>
          <% end %>
          <% if policy(@spooner).destroy? %>
            <button class="btn btn-show"><%= link_to "Delete Spooner",
            spooner_path(@spooner),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
            %></button>
          <% end %>
          <% if @spooner.user != current_user %>
          <div class="d-flex justify-content-center d-grid gap-2 mx-auto">
            <button class="btn btn-show btn-lg" style="width: 100;"><%= link_to "Get Spoonin\'", new_spooner_booking_path(@spooner)  %></button>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<%# Reviews %>

  <div class="container pb-5">
    <p><strong>Reviews</strong></p>
    <%= render "reviews/new", { spooner: @spooner, review: @review }  %>
    <% if @spooner.reviews.size > 0 %>
    <p><strong>Average rating:</strong>
      <% @spooner.solid_stars.times do %>
      <iconify-icon icon="material-symbols:star"></iconify-icon>
      <% end %>
      <% @spooner.half_stars.times do %>
      <iconify-icon icon="material-symbols:star-half"></iconify-icon>
      <% end %>
      <% @spooner.empty_stars.times do %>
      <iconify-icon icon="material-symbols:star-outline"></iconify-icon>
      <% end %>
    </p>
    <ul class="list-group">
      <% @spooner.reviews.each do |review| %>
        <li class="list-group-item">
          <% review.rating.times do %>
          <iconify-icon icon="material-symbols:star"></iconify-icon>
          <% end %>
          <% (5 - review.rating).times do %>
          <iconify-icon icon="material-symbols:star-outline"></iconify-icon>
          <% end %>
          <small><%= link_to "[Delete]",
          review_path(review),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} if policy(review).destroy? %></small>
        </li>
        <li class="list-group-item mb-3"><em><%= review.content %></em></li>
      <% end %>
    </ul>
    <br>
    <% end %>
  </div>
</body>